### ISSUE TITLE
Handle data of type "rdf:Property"/"rdfs:Class" as schema element data

### ISSUE THREAD

**Issue by aaj3f** [fluree/db#394] opened 2023-02-20 17:21 UTC
### Description

Currently, there is a subject id range reserved for schema elements (e.g. classes and properties). which generally supports lookups for performant schema-caching. When classes and properties are used in a transaction, they are assigned subject ids in this range. However, it is currently not possible to add explicit data elements of type "rdf:Property" or "rdfs:Class" and have them assigned to this schema range of subject ids. In other words, the following two transactions (one to add a property explicitly, the second to attempt to use that property) would NOT refer to the same subject id on `ex:description`:

```json
{
    "ledger": "fluree-jld/bugb1",
    "txn": {
        "@context": {
            "ex": "http://example.org/"
        },
        "@id": "ex:description",
        "@type": "rdf:Property",
        "rdfs:label": "description"
    }
}
```

```json
{
    "ledger": "fluree-jld/bugb1",
    "txn": {
        "@context": {
            "ex": "http://example.org/"
        },
        "@id": "ex:fluree",
        "@type": "schema:Organization",
        "ex:description": "An organization with a great description"
    }
}
```

### Acceptance Criteria

- This story hopes for a short-term fix for data added of type "rdf:Property" or "rdfs:Class", such that those data items are treated as schema elements and persisted accordingly to allow for their implicit use as classes and properties of subsequent transactions/queries
- Longer-term work that re-evaluates schema caching more broadly should NOT be a part of this ticket, and should be tasked separately

**Comment by dpetran** [comment] 2023-02-21 16:46
I'd just like to clarify - this is for performance optimization, not a bug in what results are returned, right?

**Comment by aaj3f** [comment] 2023-02-21 17:12
@dpetran -- I don't know if it's a "bug" but it's much more than performance optimization. Let's say that I want to pre-define a set of classes and properties before I use them to model data that I'm inserting. I might even just take a vocab payload from schema.org to predefine `schema:Person` and all the properties in the domain of `schema:Person`. If I add that data and THEN add objects of type, `schema:Person`, with all the properties I just defined, Fluree currently does not leverage all the classes/properties I just added, it creates new ones, and it creates them in the subject id range reserved for schema elements. So...

Current Behavior: Any data I add explicitly (in this case, data of type `rdf:Property` or `rdfs:Class`) does not get added to the subject id range reserved for schema elements
Current Problem: I cannot predefine schema element data (in this case, I cannot add data of type `rdf:Property` or `rdfs:Class`) and then use those classes and properties in transactions of other data. If I attempt to, I find that new facts/flakes are created to represent, say, a class of `schema:Person`, even if I had already added an `@id` of `schema:Person` as part of `@type: rdfs:Class`
Needed Solution: If I add data of type `rdf:Property` or `rdfs:Class`, Fluree should use the subject id range reserved for schema elements for those items, so then when it uses its cached schema to evaluate if those classes/properties already exist, it will find them, instead of creating new ones

**Comment by dpetran** [comment] 2023-02-21 17:24
I think I understand, but when I run the example the `ex:description` subject gets a subject id of `1001`, which I think is in the "schema" range. And when I check the db's schema cache there is an entry for the description: 
```
(-> db :schema :pred (get 1001))
{:id 1001,
     :class false,
     :idx? true,
     :ref? false,
     :subclassOf [],
     :equivalentProperty [],
     :iri "http://example.org/ns/description"}
```

Is there more to the setup that makes us think that this isn't being handled properly?

**Comment by dpetran** [comment] 2023-02-21 17:31
Here's my reproduction setup, for the record:
```
(def conn @(fluree/connect {:method :memory
                              :storage-path "dev/data"
                              :defaults
                              {:context test-utils/default-context
                               :did
                               {:id "did:fluree:Tf1sbdG5vZrMvdcfpVN9btp3nkYPKgWNu2H",
                                :public "020154853f38da17df4f1ad6e5cd1c424bf82066708ece89514b975c807aeccc60",
                                :private "ccd238808e29bda00a62cd27c592d1ef16efdf1f473854e6b276409f36435aed"}}}))

  (def ledger @(fluree/create conn "schema-bug" {:context {:ex "http://example.org/ns/"}}))

  (def db1 @(fluree/stage (fluree/db ledger) {:id :ex/description
                                              :type :rdf/Property
                                              :rdfs/label "description"}))

  (def db2 @(fluree/stage db1 {:id :ex/dan
                               :ex/x 55
                               :ex/description "A super cool dude"}))

(-> db2 :novelty :spot)
  #{#Flake [211106232532992 0 "http://example.org/ns/dan" 1 -1 true nil]
    #Flake [211106232532992 1001 "A super cool dude" 1 -1 true nil]
    #Flake [211106232532992 1003 55 8 -1 true nil]
    #Flake [1003 0 "http://example.org/ns/x" 1 -1 true nil]
    #Flake [1002 0 "http://www.w3.org/2000/01/rdf-schema#label" 1 -1 true nil]
    #Flake [1001 0 "http://example.org/ns/description" 1 -1 true nil]
    #Flake [1001 200 204 0 -1 true nil]
    #Flake [1001 1002 "description" 1 -1 true nil]
    #Flake [204 0 "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property" 1 -1 true nil]
    #Flake [204 200 203 0 -1 true nil]
    #Flake [203 0 "http://www.w3.org/2000/01/rdf-schema#Class" 1 0 true nil]
    #Flake [203 0 "http://www.w3.org/2000/01/rdf-schema#Class" 1 -1 true nil]
    #Flake [200 0 "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" 1 0 true nil]
    #Flake [200 0 "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" 1 -1 true nil]
    #Flake [0 0 "@id" 1 0 true nil] #Flake [0 0 "@id" 1 -1 true nil]}

```

the `:ex/description` subject got subject id 1001, which is in the schema territory
the `:ex/dan` subject got subject id 211106232532992, which isn't

I'll try next with `rdfs:Class`.

**Comment by dpetran** [comment] 2023-02-27 18:43
Closing this as we weren't able to get this behavior with rdfs:Class either.

**Closed** 2023-02-27 18:44 UTC
Labels: enhancement
