### ISSUE TITLE
Some combinations of time values cause indexing errors

### ISSUE THREAD

**Issue by mpoffald** [fluree/db#589] opened 2023-10-03 22:21 UTC
The types `xsd:dateTime`, `xsd:date`, and `xsd:time` can have values with or without time zones. However, when we create flakes for values with these types, we coerce them into `java.time` objects, which results in different _java_ types depending on whether there's a time zone. 

As a result, transacting two values for the same predicate with the same type, but where one has a time zone and one does not, causes errors in our comparators:

```clj
(def conn @(fluree/connect {:method :file
                                :storage-path "dev/data"
                                :defaults
                                {:context (merge test-utils/default-str-context {"ex" "http://example.org/ns/"})}}))
 (def    ledger @(fluree/create conn "user/test"))
 (def    db @(fluree/stage
              (fluree/db ledger)
                [{"@id" "ex:Foo1",
                  "@type" "ex:Bar",
                  "ex:created" {"@type" "xsd:dateTime" 
                                ;;has a time zone, becomes OffsetDateTime
                                "@value" "2023-04-01T00:00:00.000Z"}}
                 {"@id" "ex:Foo2"
                  "@type" "ex:Bar"
                  "ex:created" {"@type" "xsd:dateTime"
                                 ;;no time zone, becomes LocalDateTime
                                "@value" "2023-04-01T00:00:00.000"}}]))
 (def    db-commit @(fluree/commit! ledger db))

;;=>
ERROR fluree.db.json-ld.api - #error {
 :cause "class java.time.LocalDateTime cannot be cast to class java.time.OffsetDateTime (java.time.LocalDateTime and java.time.OffsetDateTime are in module java.base of loader 'bootstrap')"
 :via
 [{:type java.lang.ClassCastException
   :message "class java.time.LocalDateTime cannot be cast to class java.time.OffsetDateTime (java.time.LocalDateTime and java.time.OffsetDateTime are in module java.base of loader 'bootstrap')"
   :at [java.time.OffsetDateTime compareTo "OffsetDateTime.java" 128]}]
 :trace
 [[java.time.OffsetDateTime compareTo "OffsetDateTime.java" 128]
  [clojure.lang.Util compare "Util.java" 153]
  [fluree.db.flake$cmp_obj invokeStatic "flake.cljc" 361]
  [fluree.db.flake$cmp_obj invoke "flake.cljc" 354]
  [fluree.db.flake$cmp_flakes_post invokeStatic "flake.cljc" 401]
  [fluree.db.flake$cmp_flakes_post invoke "flake.cljc" 398]
  [clojure.lang.AFunction compare "AFunction.java" 51]
  [clojure.data.avl$insert_BANG_ invokeStatic "avl.clj" 797]
...]}
```

**Comment by JaceRockman** [comment] 2024-03-12 22:26
Couldn't reproduce this issue. Closing the ticket.

**Closed** 2024-03-12 22:27 UTC
Labels: bug
